#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# loadtest-remote.sh — run the load-test harness (and optionally a throw-away fake
# server) on a REMOTE Linux box, e.g. one of our Nym nodes (1 Gbit uplink), because one
# laptop's uplink saturates at ~40 simulated users (docs/load-testing.md).
#
# Everything lives under /var/tmp/scrai-loadtest on the box (LT_ROOT to change; /tmp is a
# RAM tmpfs on our nodes, too small for the build) — sources, an own Rust toolchain
# (RUSTUP_HOME/CARGO_HOME inside it, nothing touches ~ or the system), binaries, results,
# server state. `clean` removes it without a trace. Nothing needs root; only the build
# tools (gcc, pkg-config, libssl-dev) must already be there (the script tells you if not).
#
#   scripts/loadtest-remote.sh install <user@host>            sync + build (10–30 min first time)
#   scripts/loadtest-remote.sh run     <user@host> <addr[,addr…]> [mode] [stages] [spread]
#                                                              detached run on the box;
#                                                              mode ping|models|chat (default ping),
#                                                              stages e.g. 50,100,150 (default 50,100),
#                                                              spread primary|all|both (default both)
#   scripts/loadtest-remote.sh status  <user@host>            tail the current run's log
#   scripts/loadtest-remote.sh fetch   <user@host>            copy results + logs to loadtest/results/remote-<host>/
#   scripts/loadtest-remote.sh server-start <user@host>       fake-payments + mock-provider server on the box
#                                                              (wipes the SDK's reply-SURB sqlite first — it goes
#                                                              inconsistent after a hard stop and then refuses to boot)
#                                                              (env: GATEWAY_MASTER, GATEWAY_FALLBACK, MOCK)
#   scripts/loadtest-remote.sh server-addr  <user@host>       its addresses (comma-joined, for `run`)
#   scripts/loadtest-remote.sh server-stop  <user@host>
#   scripts/loadtest-remote.sh clean   <user@host>            rm -rf the root dir (everything)
#
# Knobs for `run` (env): REQUESTS (default 10), THINK_MS (default 5000), RAMP_MS (default 250),
# TIMEOUT_MS (default 120000), EXTRA (extra harness flags, e.g. "--surbs 10").
# Sizing: each simulated user is a full Nym client ≈ 50 MB RSS → ~120 users per 8 GB box.
# ---------------------------------------------------------------------------
set -euo pipefail
CMD="${1:-}"; HOST="${2:-}"
[ -n "$CMD" ] && [ -n "$HOST" ] || { sed -n 2,30p "$0" | sed 's/^# \{0,1\}//'; exit 2; }
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Root on the box. /tmp is often a RAM-backed tmpfs (5.8 GB on our nodes) — too small for
# a nym-sdk build — so the default is /var/tmp (disk). Override with LT_ROOT.
R="${LT_ROOT:-/var/tmp/scrai-loadtest}"
CM_SOCK="${TMPDIR:-/tmp}/scrai-lt-cm-$$"
SSH_OPTS=(-o ControlMaster=auto -o "ControlPath=${CM_SOCK}" -o ControlPersist=120)
cleanup() { ssh "${SSH_OPTS[@]}" -O exit "$HOST" >/dev/null 2>&1 || true; rm -f "$CM_SOCK"; }
trap cleanup EXIT
rssh() { ssh "${SSH_OPTS[@]}" "$HOST" "$@"; }
# Toolchain lives inside $R; `cargo` from the box's PATH is used only when present.
ENV_PREFIX="export RUSTUP_HOME=$R/rustup CARGO_HOME=$R/cargo PATH=$R/cargo/bin:\$PATH;"

case "$CMD" in
install)
  echo "→ checking build tools on $HOST …"
  rssh 'for t in cc pkg-config make; do command -v $t >/dev/null || { echo "missing: $t — install with: sudo apt-get install -y build-essential pkg-config libssl-dev"; exit 1; }; done; echo ok'
  echo "→ syncing sources → $HOST:$R/src …"
  rssh "mkdir -p $R/src $R/results $R/logs"
  rsync -az --delete -e "ssh ${SSH_OPTS[*]}" \
    --exclude 'target/' --exclude 'fuzz/' --exclude 'results/' \
    "$SRC/core" "$SRC/loadtest" "$SRC/server" "$SRC/Cargo.lock" "$SRC/pricing.json" "$HOST:$R/src/"
  WS_VER=$(sed -n '/^\[workspace\.package\]/,/^\[/p' "$SRC/Cargo.toml" | sed -n 's/^version *= *"\([^"]*\)".*/\1/p' | head -1)
  rssh "cat > $R/src/Cargo.toml <<CT
# generated by loadtest-remote.sh — harness + server only
[workspace]
resolver = \"2\"
members = [\"core\", \"loadtest\", \"server\"]
[workspace.package]
version = \"$WS_VER\"
[profile.release]
opt-level = 1
CT"
  echo "→ rust toolchain (private, under $R) …"
  rssh "$ENV_PREFIX command -v cargo >/dev/null && cargo --version || (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --no-modify-path >/dev/null && cargo --version)"
  echo "→ building scrai-loadtest + scrai-server on the box (detached; the first build compiles nym-sdk — 10–30 min) …"
  rssh "$ENV_PREFIX cd $R/src && nohup cargo build --release -p scrai-loadtest -p scrai-server > $R/logs/build.log 2>&1 &
    echo started"
  echo "→ follow with: scripts/loadtest-remote.sh status $HOST   (shows the build until the binaries exist)"
  ;;

run)
  ADDR="${3:-}"; MODE="${4:-ping}"; STAGES="${5:-50,100}"; SPREAD="${6:-both}"
  [ -n "$ADDR" ] || { echo "run: server address(es) required" >&2; exit 2; }
  REQUESTS="${REQUESTS:-10}"; THINK_MS="${THINK_MS:-5000}"; RAMP_MS="${RAMP_MS:-250}"; TIMEOUT_MS="${TIMEOUT_MS:-120000}"; EXTRA="${EXTRA:-}"
  TS=$(date +%Y%m%d-%H%M%S)
  PRIMARY="${ADDR%%,*}"
  case "$SPREAD" in all) V="all";; both) V="primary all";; *) V="primary";; esac
  # The run script itself goes to the box and runs under nohup; a `top` sampler rides along.
  rssh "cat > $R/run-$TS.sh <<RS
#!/bin/bash
cd $R
ulimit -n 65536 2>/dev/null || true
( while true; do echo \"[cpu \\\$(date +%T)] \\\$(top -bn1 | grep -E 'scrai-loadtest|scrai-server|load average' | tr -s ' ' | cut -c1-90 | paste -sd'|' -)\"; sleep 15; done ) &
SAMPLER=\\\$!
for N in \$(echo '$STAGES' | tr , ' '); do
  for V in $V; do
    if [ \"\\\$V\" = all ]; then TO='$ADDR'; else TO='$PRIMARY'; fi
    echo \"================ stage: \\\$N clients · $MODE · \\\$V (\\\$(echo \\\$TO | awk -F, '{print NF}') address(es)) ================\"
    ./src/target/release/scrai-loadtest --server \"\\\$TO\" --mode $MODE --clients \\\$N --requests $REQUESTS --think-ms $THINK_MS --ramp-ms $RAMP_MS --timeout-ms $TIMEOUT_MS --out results --label remote-$MODE-\\\${N}c-\\\$V $EXTRA 2>&1 | grep -vE ' WARN | INFO '
  done
done
kill \\\$SAMPLER 2>/dev/null
echo 'series done'
RS
chmod +x $R/run-$TS.sh; setsid nohup $R/run-$TS.sh > $R/logs/run-$TS.log 2>&1 < /dev/null &
disown; echo \"started run-$TS (log: $R/logs/run-$TS.log)\""
  echo "→ follow with: scripts/loadtest-remote.sh status $HOST   ·   results: scripts/loadtest-remote.sh fetch $HOST"
  ;;

status)
  # A build in progress (or failed) shows first; then the latest run.
  rssh "if [ ! -x $R/src/target/release/scrai-loadtest ]; then echo '== build (binary not there yet)'; tail -5 $R/logs/build.log 2>/dev/null; pgrep -x cargo >/dev/null && echo '(building)' || echo '(build not running — see build.log)'; exit 0; fi;
    L=\$(ls -t $R/logs/run-*.log 2>/dev/null | head -1); [ -n \"\$L\" ] || { echo 'binaries ready — no run yet'; exit 0; }; echo \"== \$L\"; grep -E '^=+ stage|^ping |^chat |^models |^connect |^session.status |^requests |series done|^\[cpu' \"\$L\" | tail -25; pgrep -f run-.*\.sh >/dev/null && echo '(still running)' || echo '(finished)'"
  ;;

fetch)
  DEST="$SRC/loadtest/results/remote-${HOST#*@}"
  mkdir -p "$DEST"
  rsync -az -e "ssh ${SSH_OPTS[*]}" "$HOST:$R/results/" "$DEST/" 2>/dev/null || true
  rsync -az -e "ssh ${SSH_OPTS[*]}" "$HOST:$R/logs/" "$DEST/logs/" 2>/dev/null || true
  echo "✓ results → $DEST"; ls "$DEST"
  ;;

server-start)
  MOCK="${MOCK:-1500:800}"
  rssh "mkdir -p $R/server/data && cat > $R/server/.env <<ENV
FAKE_PAYMENTS=1
MOCK_PROVIDER=$MOCK
DATA=$R/server/data
PRICING=$R/src/pricing.json
MIX_BURST=1
MAX_INFLIGHT_CHATS=${MAX_INFLIGHT_CHATS:-64}
${GATEWAY_MASTER:+GATEWAY_MASTER=$GATEWAY_MASTER}
${GATEWAY_FALLBACK:+GATEWAY_FALLBACK=$GATEWAY_FALLBACK}
${MIX_CLIENTS:+MIX_CLIENTS=$MIX_CLIENTS}
ENV
cd $R/server && rm -f data/addresses.txt data/.nym-server/persistent_reply_store.sqlite* && setsid nohup $R/src/target/release/scrai-server > $R/logs/server.log 2>&1 < /dev/null &
disown; echo started"
  echo "→ waiting for the server's mixnet address(es) …"
  for _ in $(seq 1 120); do
    N=$(rssh "cat $R/server/data/addresses.txt 2>/dev/null | wc -l" | tr -d ' ')
    [ "${N:-0}" -ge "${MIX_CLIENTS:-1}" ] && break
    sleep 3
  done
  rssh "cat $R/server/data/addresses.txt; grep -E 'MOCK|FAKE|identities|FATAL' $R/logs/server.log | head -5"
  ;;

server-addr)
  rssh "paste -sd, $R/server/data/addresses.txt"
  ;;

server-stop)
  # SIGTERM, not SIGINT: a process started with `nohup … &` from a non-interactive shell
  # ignores SIGINT. The server handles SIGTERM the same way (clean disconnect + flush).
  # -x (exact process name): a -f pattern also matches the ssh command line carrying it,
  # which kills our own shell first and the server never.
  rssh "pkill -TERM -x scrai-server; for i in 1 2 3 4 5 6 7 8 9 10; do pgrep -x scrai-server >/dev/null || break; sleep 1; done; pgrep -x scrai-server >/dev/null && echo 'still running' || echo stopped"
  ;;

clean)
  rssh "pkill -TERM -x scrai-server 2>/dev/null; pkill -TERM -x scrai-loadtest 2>/dev/null; pkill -TERM -x cargo 2>/dev/null; sleep 3; rm -rf $R && echo 'removed $R'"
  ;;

*)
  echo "unknown command $CMD" >&2; exit 2 ;;
esac
